coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "hitbox-test/**"
  - "**/tests/**"
  - "**/benches/**"
  - "**/examples/**"
